export const validAssistantSuggestion = () => ({
  title: "Учебный пожар в мастерской",
  category: "fire" as const,
  difficulty: 3,
  summary: "Задымление в учебной мастерской с одним пострадавшим.",
  persona: {
    gender: "female" as const,
    displayName: "Елена Учебная",
    ageYears: 42,
    condition: "Напугана, находится снаружи",
    speechStyle: "Говорит коротко, сбивается и просит прислать помощь.",
    backgroundSounds: "Сирена во дворе",
    baselinePanicLevel: 2,
    baseSpeechRate: 1.1,
  },
  openingLine: "Алло, у нас дым в мастерской!",
  fallbackLine: "Я не знаю, пожалуйста, приезжайте скорее.",
  expectedServices: ["fire", "ambulance"] as const,
  facts: [
    {
      key: "incident_type",
      promptValue: "В мастерской сильное задымление.",
      displayLabel: "Тип происшествия",
      severity: "normal" as const,
      cardField: "category" as const,
      cardValue: "пожар",
      contentKeywords: ["дым", "мастерск"],
      disclosureType: "immediate" as const,
      questionKeywords: ["что случилось"],
      priority: 10,
    },
    {
      key: "scene",
      promptValue: "Происшествие происходит во дворе учебной мастерской.",
      displayLabel: "Место происшествия",
      severity: "normal" as const,
      cardField: "object_type" as const,
      cardValue: "двор мастерской",
      contentKeywords: ["двор", "мастерск"],
      disclosureType: "on_question" as const,
      questionKeywords: ["адрес", "где"],
      priority: 9,
    },
    {
      key: "victim",
      promptValue: "Один человек надышался дымом, он в сознании.",
      displayLabel: "Пострадавший",
      severity: "heavy" as const,
      cardField: "victims_total" as const,
      cardValue: "1",
      contentKeywords: ["человек", "дыш"],
      disclosureType: "on_question" as const,
      questionKeywords: ["пострадав", "люди"],
      priority: 8,
    },
  ],
  mandatoryQuestions: [
    {
      text: "Уточнить тип места происшествия",
      satisfiedByFactKeys: ["scene"],
      isCritical: true,
    },
    {
      text: "Уточнить наличие пострадавших",
      satisfiedByFactKeys: ["victim"],
      isCritical: true,
    },
  ],
  referenceNotes:
    "Проверить место происшествия, пострадавшего и выбор двух служб.",
});
