export const validAssistantSuggestion = () => ({
  title: "Учебный пожар в мастерской",
  category: "fire" as const,
  difficulty: 3,
  summary: "Задымление в учебной мастерской с одним пострадавшим.",
  persona: {
    gender: "female" as const,
    displayName: "Елена Учебная",
    ageYears: 42,
    condition: "Напугана, находится снаружи",
    speechStyle: "Говорит коротко, сбивается и просит прислать помощь.",
    backgroundSounds: "Сирена во дворе",
    baselinePanicLevel: 2,
    baseSpeechRate: 1.1,
  },
  openingLine: "Алло, у нас дым в мастерской!",
  fallbackLine: "Я не знаю, пожалуйста, приезжайте скорее.",
  expectedServices: ["fire", "ambulance"] as const,
  location: {
    terrain: "city_block" as const,
    city: "Учебный город",
    street: "Учебная",
    house: "12",
    details: "Мастерская во дворе",
    exactPoint: { lat: 55.751244, lon: 37.618423 },
    locatorLabel: "Базовая станция: Учебный квартал",
    callerNumber: "+7 000 000-00-00",
  },
  facts: [
    {
      key: "incident_type",
      promptValue: "В мастерской сильное задымление.",
      displayLabel: "Тип происшествия",
      severity: "normal" as const,
      cardField: "category" as const,
      cardValue: "пожар",
      contentKeywords: ["дым", "мастерск"],
      disclosureType: "immediate" as const,
      questionKeywords: ["что случилось"],
      priority: 10,
    },
    {
      key: "address",
      promptValue: "Адрес: Учебная улица, дом 12.",
      displayLabel: "Адрес",
      severity: "normal" as const,
      cardField: "street" as const,
      cardValue: "Учебная",
      contentKeywords: ["учебн", "дом"],
      disclosureType: "on_question" as const,
      questionKeywords: ["адрес", "где"],
      priority: 9,
    },
    {
      key: "victim",
      promptValue: "Один человек надышался дымом, он в сознании.",
      displayLabel: "Пострадавший",
      severity: "heavy" as const,
      cardField: "victims_total" as const,
      cardValue: "1",
      contentKeywords: ["человек", "дыш"],
      disclosureType: "on_question" as const,
      questionKeywords: ["пострадав", "люди"],
      priority: 8,
    },
  ],
  mandatoryQuestions: [
    {
      text: "Уточнить точный адрес происшествия",
      satisfiedByFactKeys: ["address"],
      isCritical: true,
    },
    {
      text: "Уточнить наличие пострадавших",
      satisfiedByFactKeys: ["victim"],
      isCritical: true,
    },
  ],
  referenceNotes: "Проверить адрес, пострадавшего и выбор двух служб.",
});
