/**
 * Application error codes for i18n support.
 * Frontend uses these codes to display localized error messages.
 *
 * Convention: DOMAIN_ACTION_REASON
 * Example: USER_CREATE_EMAIL_EXISTS
 */
export const ErrorCodes = {
  // ── Common ─────────────────────────────────────────────────
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  DATABASE_ERROR: "DATABASE_ERROR",
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",

  // ── Auth ───────────────────────────────────────────────────
  AUTH_LOGIN_INVALID_CREDENTIALS: "AUTH_LOGIN_INVALID_CREDENTIALS",
  AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  // One code for every refresh failure — unknown, expired, revoked or replayed.
  // A distinguishable reason only helps an attacker probe tokens.
  AUTH_REFRESH_TOKEN_INVALID: "AUTH_REFRESH_TOKEN_INVALID",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_ROLE_FORBIDDEN: "AUTH_ROLE_FORBIDDEN",
  AUTH_LAST_ADMIN_REQUIRED: "AUTH_LAST_ADMIN_REQUIRED",

  // ── Конструктор сценариев ──────────────────────────────────
  SCENARIO_CODE_EXISTS: "SCENARIO_CODE_EXISTS",
  SCENARIO_PERSONA_CODE_EXISTS: "SCENARIO_PERSONA_CODE_EXISTS",
  SCENARIO_ASSISTANT_UNAVAILABLE: "SCENARIO_ASSISTANT_UNAVAILABLE",
  SCENARIO_ASSISTANT_INVALID_DRAFT: "SCENARIO_ASSISTANT_INVALID_DRAFT",
  SCENARIO_GENERATION_LIMIT: "SCENARIO_GENERATION_LIMIT",
  SCENARIO_GENERATION_JOB_NOT_FOUND: "SCENARIO_GENERATION_JOB_NOT_FOUND",
  SCENARIO_NOT_FOUND: "SCENARIO_NOT_FOUND",
  SCENARIO_VERSION_NOT_FOUND: "SCENARIO_VERSION_NOT_FOUND",
  // Пока преподаватель правил, опубликована более новая версия: его правка
  // затёрла бы чужую.
  SCENARIO_VERSION_STALE: "SCENARIO_VERSION_STALE",
  SCENARIO_CODE_IMMUTABLE: "SCENARIO_CODE_IMMUTABLE",

  // ── Классификатор происшествий ─────────────────────────────
  CLASSIFIER_IMPORT_INVALID: "CLASSIFIER_IMPORT_INVALID",
  CLASSIFIER_FILE_REQUIRED: "CLASSIFIER_FILE_REQUIRED",
  CLASSIFIER_VERSION_NOT_FOUND: "CLASSIFIER_VERSION_NOT_FOUND",
  CLASSIFIER_ACTIVE_VERSION_NOT_FOUND: "CLASSIFIER_ACTIVE_VERSION_NOT_FOUND",
  CLASSIFIER_ENTRY_NOT_FOUND: "CLASSIFIER_ENTRY_NOT_FOUND",
  CLASSIFIER_QUALIFIER_INVALID: "CLASSIFIER_QUALIFIER_INVALID",

  // ── Учебные группы и назначения ─────────────────────────────────────────
  GROUP_NOT_FOUND: "GROUP_NOT_FOUND",
  GROUP_CODE_ALREADY_EXISTS: "GROUP_CODE_ALREADY_EXISTS",
  GROUP_MEMBER_EXISTS: "GROUP_MEMBER_EXISTS",
  GROUP_MEMBER_NOT_FOUND: "GROUP_MEMBER_NOT_FOUND",
  GROUP_ARCHIVED: "GROUP_ARCHIVED",
  GROUP_HAS_ASSIGNMENTS: "GROUP_HAS_ASSIGNMENTS",
  GROUP_HAS_RUNNING_ASSIGNMENTS: "GROUP_HAS_RUNNING_ASSIGNMENTS",
  ASSIGNMENT_NOT_FOUND: "ASSIGNMENT_NOT_FOUND",
  ASSIGNMENT_NOT_AVAILABLE: "ASSIGNMENT_NOT_AVAILABLE",
  ASSIGNMENT_INVALID_DUE_DATE: "ASSIGNMENT_INVALID_DUE_DATE",
  ASSIGNMENT_STATE_INVALID: "ASSIGNMENT_STATE_INVALID",
  ASSIGNMENT_MAX_ATTEMPTS_REACHED: "ASSIGNMENT_MAX_ATTEMPTS_REACHED",
  ASSIGNMENT_ATTEMPT_ACTIVE: "ASSIGNMENT_ATTEMPT_ACTIVE",
  ASSIGNMENT_HAS_ACTIVE_ATTEMPTS: "ASSIGNMENT_HAS_ACTIVE_ATTEMPTS",
  TRAINING_SESSION_NOT_ACTIVE: "TRAINING_SESSION_NOT_ACTIVE",

  // ── Отчёты преподавателя ──────────────────────────────────────────────
  REPORT_INVALID_PERIOD: "REPORT_INVALID_PERIOD",
  REPORT_TOO_LARGE: "REPORT_TOO_LARGE",

  // ── Геокодирование ─────────────────────────────────────────
  GEOCODING_ADDRESS_NOT_FOUND: "GEOCODING_ADDRESS_NOT_FOUND",
  GEOCODING_UNAVAILABLE: "GEOCODING_UNAVAILABLE",
  GEOCODING_CALL_NOT_ACTIVE: "GEOCODING_CALL_NOT_ACTIVE",

  // ── Учебный звонок ─────────────────────────────────────────
  // Чужой звонок неотличим от несуществующего: знать чужие идентификаторы
  // сессий оператору незачем.
  CALL_NOT_FOUND: "CALL_NOT_FOUND",
  INCIDENT_CARD_CLOSED: "INCIDENT_CARD_CLOSED",
  INCIDENT_CARD_NOT_READY: "INCIDENT_CARD_NOT_READY",
  RECORDING_NOT_FOUND: "RECORDING_NOT_FOUND",

  // ── Практическое занятие ДДС ───────────────────────────────
  DDS_EXERCISE_NOT_FOUND: "DDS_EXERCISE_NOT_FOUND",
  DDS_SCENARIO_NOT_READY: "DDS_SCENARIO_NOT_READY",
  DDS_STATUS_COMMENT_REQUIRED: "DDS_STATUS_COMMENT_REQUIRED",
  DDS_STATUS_TRANSITION_INVALID: "DDS_STATUS_TRANSITION_INVALID",
  DDS_STATUS_TRANSITION_CONFLICT: "DDS_STATUS_TRANSITION_CONFLICT",
  DDS_CREW_NOT_NOTIFIED: "DDS_CREW_NOT_NOTIFIED",
  DDS_LESSON_NOT_FOUND: "DDS_LESSON_NOT_FOUND",
  DDS_LESSON_FINISHED: "DDS_LESSON_FINISHED",
  DDS_LESSON_SERVICE_INVALID: "DDS_LESSON_SERVICE_INVALID",
  DDS_REFERENCE_NOT_FOUND: "DDS_REFERENCE_NOT_FOUND",
  DDS_REPORT_NOT_FOUND: "DDS_REPORT_NOT_FOUND",
  TELEPHONY_DISABLED: "TELEPHONY_DISABLED",
  TELEPHONY_UNAVAILABLE: "TELEPHONY_UNAVAILABLE",
  TELEPHONY_WORKSTATION_REQUIRED: "TELEPHONY_WORKSTATION_REQUIRED",
  TELEPHONY_BROWSER_PHONE_UNAVAILABLE: "TELEPHONY_BROWSER_PHONE_UNAVAILABLE",
  TELEPHONY_CREW_UNAVAILABLE: "TELEPHONY_CREW_UNAVAILABLE",
  TELEPHONY_CALL_CONFLICT: "TELEPHONY_CALL_CONFLICT",

  // ── Методические материалы ───────────────────────────────────────────────
  METHODICAL_MATERIAL_NOT_FOUND: "METHODICAL_MATERIAL_NOT_FOUND",
  METHODICAL_SECTION_NOT_FOUND: "METHODICAL_SECTION_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
