export const env = {
  NODE_ENV: "test",
  DATABASE_URL: process.env.DATABASE_URL,
  JWT_SECRET: process.env.JWT_SECRET,
  JWT_ACCESS_TTL_SECONDS: 3600,
  AUTH_REFRESH_TOKEN_TTL_SECONDS: 2_592_000,
  AUTH_SESSION_TTL_SECONDS: 7_776_000,
  ASR_SERVICE_URL: "http://127.0.0.1:8787",
  TOOLS_LLM_TIMEOUT_MS: 5_000,
  NOMINATIM_BASE_URL: "http://127.0.0.1:9",
  NOMINATIM_CACHE_TTL_SECONDS: 60,
  NOMINATIM_REQUEST_TIMEOUT_MS: 500,
  NOMINATIM_USER_AGENT: "system-112-e2e",
} as const;
